### ISSUE TITLE
rm command fails if file is added to index but not committed. Need to be more subtle about this.

### ISSUE THREAD

**Issue by PDWhittington** [PDWhittington/todo#156]

**Comment by PDWhittington** [comment]
philipwhittington@penguin:~/year-of-phil$ todo 10/3
philipwhittington@penguin:~/year-of-phil$ todo rm 10/3
Command line interpreted as RemoveCommand

The app threw the following exception:

LibGit2Sharp.RemoveFromIndexException: Unable to remove file 'todo/todo-2022-03-10.md', as it has changes staged in the index. You can call the Remove() method with removeFromWorkingDirectory=false if you want to remove it from the index only.
   at Todo.Execution.RemoveCommandExecutor.Execute(RemoveCommand command) in /home/philipwhittington/todo/src/todo/Execution/RemoveCommandExecutor.cs:line 41
   at Todo.Execution.CommandExecutorBase`1.ExecuteCommandBase(CommandBase command) in /home/philipwhittington/todo/src/todo/Execution/CommandExecutorBase.cs:line 23
   at Todo.TodoService.PerformTask() in /home/philipwhittington/todo/src/todo/TodoService.cs:line 30
   at Program.<Main>$(String[] args) in /home/philipwhittington/todo/src/todo/Program.cs:line 10
Unhandled exception. LibGit2Sharp.RemoveFromIndexException: Unable to remove file 'todo/todo-2022-03-10.md', as it has changes staged in the index. You can call the Remove() method with removeFromWorkingDirectory=false if you want to remove it from the index only.
   at Todo.Execution.RemoveCommandExecutor.Execute(RemoveCommand command) in /home/philipwhittington/todo/src/todo/Execution/RemoveCommandExecutor.cs:line 41
   at Todo.Execution.CommandExecutorBase`1.ExecuteCommandBase(CommandBase command) in /home/philipwhittington/todo/src/todo/Execution/CommandExecutorBase.cs:line 23
   at Todo.TodoService.PerformTask() in /home/philipwhittington/todo/src/todo/TodoService.cs:line 30
   at Program.<Main>$(String[] args) in /home/philipwhittington/todo/src/todo/Program.cs:line 10
Aborted (core dumped)
philipwhittington@penguin:~/year-of-phil$
