### ISSUE TITLE
Date parser doesn't seem to recognise dd/mm/yy or dd/mm/yyyy (not urgent right now) -- appears culture dependent

### ISSUE THREAD

**Issue by PDWhittington** [PDWhittington/todo#93]
To reproduce:

philipwhittington@penguin:~/year-of-phil$ todo 18/8/2021
The app threw the following exception:

System.Exception: Date not recognised in command
   at Todo.CommandFactories.CreateOrShowDayListCommandFactory.TryGetCommand(String commandLine) in /home/philipwhittington/todo/src/todo/CommandFactories/CreateOrShowDayListCommandFactory.cs:line 39
   at Todo.StateAndConfig.CommandProvider.GetCommand() in /home/philipwhittington/todo/src/todo/StateAndConfig/CommandProvider.cs:line 32
   at Todo.TodoService.PerformTask() in /home/philipwhittington/todo/src/todo/TodoService.cs:line 21
   at Program.<Main>$(String[] args) in /home/philipwhittington/todo/src/todo/Program.cs:line 10
Unhandled exception. System.Exception: Date not recognised in command
   at Todo.CommandFactories.CreateOrShowDayListCommandFactory.TryGetCommand(String commandLine) in /home/philipwhittington/todo/src/todo/CommandFactories/CreateOrShowDayListCommandFactory.cs:line 39
   at Todo.StateAndConfig.CommandProvider.GetCommand() in /home/philipwhittington/todo/src/todo/StateAndConfig/CommandProvider.cs:line 32
   at Todo.TodoService.PerformTask() in /home/philipwhittington/todo/src/todo/TodoService.cs:line 21
   at Program.<Main>$(String[] args) in /home/philipwhittington/todo/src/todo/Program.cs:line 10
Aborted (core dumped)

**Comment by PDWhittington** [comment]
Changed on Linux with advice from: https://serverfault.com/questions/54591/how-to-install-change-locale-on-debian

Edit /etc/default/locale and set the contents to:

LANG="nl_NL.UTF-8"
You can check which locales you currently have generated using:

locale -a
You can generate more by editing /etc/locale.gen and uncommenting the lines for the locales that you want to enable. Then you can generate them by running the command:

locale-gen
You can find a list of supported locales in /usr/share/i18n/SUPPORTED

There is more information available on the [Debian wiki](http://wiki.debian.org/Locale).
